Repository UnimibSoftEngCourse2022/progetto-birra-1-beer2beer, pull requests merged in 2022-01, with the labels that each got.

#17 Skip welcome fragment and Splash Screen
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/beer2beer/MainActivity.kt
  app/src/main/java/com/example/beer2beer/fragments/GetStartedFragment.kt
  app/src/main/java/com/example/beer2beer/fragments/SettingsFragment.kt
  app/src/main/res/drawable/ic_logo_splash.xml
  app/src/main/res/layout/fragment_brew.xml
  app/src/main/res/layout/fragment_cart.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_recipes.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/menu/bottom_navigation_view.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/splash.xml
  app/src/main/res/values/strings.xml
Labels: Feature, UI

#21 Dev/layout welcome
  app/src/main/res/drawable/bottom_navigation_selector.xml
  app/src/main/res/drawable/ic_logo_welcome.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_get_started.xml
  app/src/main/res/layout/fragment_welcome.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: UI

#23 Bottom nav view
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/beer2beer/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/bottom_navigation_view.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
Labels: Feature

#29 Dev/layout setting
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/values/strings.xml
Labels: UI

#34 Dev/homepage
  .idea/misc.xml
  app/build.gradle
  app/schemas/com.example.beer2beer.database.AppDatabase/1.json
  app/src/main/java/com/example/beer2beer/MainActivity.kt
  app/src/main/java/com/example/beer2beer/SharedViewModel.kt
  app/src/main/java/com/example/beer2beer/adapters/IngredientAdapter.kt
  app/src/main/java/com/example/beer2beer/adapters/RecipeAdapter.kt
  app/src/main/java/com/example/beer2beer/database/AppDatabase.kt
  app/src/main/java/com/example/beer2beer/database/RecipeDao.kt
  app/src/main/java/com/example/beer2beer/database/entities/Recipe.kt
  app/src/main/java/com/example/beer2beer/database/entities/RecipeHasIngredient.kt
  app/src/main/java/com/example/beer2beer/database/entities/RecipeInstance.kt
  app/src/main/java/com/example/beer2beer/database/entities/RecipeInstanceUseEquipment.kt
  app/src/main/java/com/example/beer2beer/fragments/AddRecipeFragment.kt
  app/src/main/java/com/example/beer2beer/fragments/HomeFragment.kt
  app/src/main/java/com/example/beer2beer/utils/SwipeToDeleteCallback.kt
  app/src/main/res/drawable/ic_baseline_add_24.xml
  app/src/main/res/drawable/ic_baseline_delete_24.xml
  app/src/main/res/drawable/radius_30_background.xml
  app/src/main/res/layout/fragment_add_recipe.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/ingredient_item.xml
  app/src/main/res/layout/recipe_item.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Feature, UI

#39 WSIBT
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/beer2beer/SharedViewModel.kt
  app/src/main/java/com/example/beer2beer/database/RecipeDao.kt
  app/src/main/java/com/example/beer2beer/database/entities/RecipeIngredients.kt
  app/src/main/java/com/example/beer2beer/fragments/BrewFragment.kt
Labels: Feature

#45 Completato il fragment Settings
  app/src/main/java/com/example/beer2beer/SharedViewModel.kt
  app/src/main/java/com/example/beer2beer/database/AppDatabase.kt
  app/src/main/java/com/example/beer2beer/database/EquipmentDao.kt
  app/src/main/java/com/example/beer2beer/database/IngredientDao.kt
  app/src/main/java/com/example/beer2beer/database/RecipeDao.kt
  app/src/main/java/com/example/beer2beer/fragments/SettingsFragment.kt
  app/src/main/java/com/example/beer2beer/repository/EquipmentRepository.kt
  app/src/main/java/com/example/beer2beer/repository/IngredientRepository.kt
  app/src/main/java/com/example/beer2beer/repository/RecipeRepository.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_settings.xml
Labels: Feature

#54 Funzione WhatShouldIBrewToday implementata
  .idea/misc.xml
  app/src/androidTest/java/com/example/beer2beer/AddRecipeNavigationTest.kt
  app/src/main/java/com/example/beer2beer/MainActivity.kt
  app/src/main/java/com/example/beer2beer/SharedViewModel.kt
  app/src/main/java/com/example/beer2beer/database/RecipeDao.kt
  app/src/main/java/com/example/beer2beer/database/entities/RecipeIngredients.kt
  app/src/main/java/com/example/beer2beer/fragments/BrewFragment.kt
  app/src/main/java/com/example/beer2beer/repository/RecipeRepository.kt
  app/src/main/res/layout/fragment_brew.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: Feature

#57 Modify layout instance recipes
  app/src/main/java/com/example/beer2beer/dialogs/AddRecipeInstanceDialogFragment.kt
  app/src/main/res/layout/dialog_add_recipe_instance.xml
  app/src/main/res/layout/dialog_edit_recipe_instance.xml
  app/src/main/res/layout/fragment_recipe_detail.xml
  app/src/main/res/layout/recipe_ingredient_item.xml
  app/src/main/res/layout/recipe_instance_item.xml
  app/src/main/res/layout/recipe_item.xml
  app/src/main/res/values/strings.xml
Labels: UI
